version: '3.4'

services:
  zk-1: &zk
    image: confluentinc/cp-zookeeper:4.0.0
    env_file:
      - zk-common.env
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: 0.0.0.0:2888:3888
    volumes:
      - zk-1:/var/lib/zookeeper/data

  kafka-1: &kafka
    image: confluentinc/cp-kafka:4.0.0
    env_file:
      - kafka-common.env
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9192,EXTERNAL://localhost:9092
      KAFKA_JMX_HOSTNAME: kafka-1
    ports:
      - 9092:9092
    volumes:
      - kafka-1:/var/lib/kafka/data

  kafka-manager:
    image: sheepkiller/kafka-manager
    environment:
      ZK_HOSTS: zk-1:2181
      JMX_PORT: 9181
      APPLICATION_SECRET: letmein
    ports:
      - 9000:9000

  # Good ol' ELK stack
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.1.2
    configs:
      - source: logstash_v3
        target: /usr/share/logstash/pipeline/main.conf
  kibana:
  # 6.1.2 produced weird error
  # FATAL CLI ERROR SyntaxError: Error parsing /usr/share/kibana/node_modules/vise/package.json: Unexpected token T in JSON at position 0
    image: docker.elastic.co/kibana/kibana-oss:6.1.1
    environment:
      ELASTICSEARCH_URL: http://es:9200
    ports:
      - 5601:5601

volumes:
  zk-1:
  kafka-1:

configs:
  logstash_v3:
    file: logstash.conf